### ISSUE TITLE
Change @mybb Twitter location

### ISSUE THREAD

**Issue by justinsoltesz** [mybb/meta#1]
The location on the @mybb Twitter account currently lists “Product of Australia.” It should be changed to say “Worldwide,” matching our GitHub location.

**Comment by kawaii** [comment]
I tried to assign this issue to Tom K. but since his Github 2FA isn't working/configured I can't. However, he's been pinged on Discord regarding it so hopefully he'll see it soon.

**Comment by justinsoltesz** [comment]
Ah, that would explain why he isn't on the team here.

**Comment by kawaii** [comment]
Sorted, assigned to @tommykent1210. :slightly_smiling_face:

**Comment by justinsoltesz** [comment]
@tommykent1210 could you take care of this?

**Comment by tommykent1210** [comment]
Done, set to "Worldwide"
